channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.12
  - nextflow=24.10.2
  - flask=3.1.0       # builds REST API
  - gevent=24.11.1    # runs flask server
  - pyyaml=6.0.2
  - numpy=2.2.1
  - pip
  - pip:
    - globus-cli=3.32
